[versions]
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

[bundles]